FROM continuumio/miniconda3:latest

# Add requirements file
ADD requirements.txt /tmp/

# Install necessary packages, Python dependencies, and cleanup
RUN apt update && apt install -y cmake g++ wget build-essential \
    && pip install --no-cache-dir -r /tmp/requirements.txt \
    && conda install -c conda-forge pybind11 \
    && wget https://github.com/microsoft/onnxruntime/releases/download/v1.14.1/onnxruntime-linux-x64-1.14.1.tgz \
    && tar -xf onnxruntime-linux-x64-1.14.1.tgz \
    && cp onnxruntime-linux-x64-1.14.1/lib/* /usr/lib/ && cp onnxruntime-linux-x64-1.14.1/include/* /usr/include/ \
    && apt-get purge -y build-essential \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
